


spring:
#  security:
#    user:
#      name: root
#      password: 1234

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/board
    username: root
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.MariaDBDialect
    database: mysql
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: false

logging:
# 로그파일 경로와 파일명 지정.
  file:
    name: logs/app.log
  level:
#    trace < debug < info < warn < error 순서의 로그레벨을 가짐.
#    info로 설정시 trace, debug로그는 출력되지 않음.
    root: info



server:
  port: 8081

